version: '3.8'

services:
  web:
    image: abhishekak71/akshopping-frontend:latest
    ports:
      - "80:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - app-network

networks:
  app-network:
    driver: overlay
