services:
  frontend:
    image: akshopping-frontend
    deploy:
      replicas: 3
      endpoint_mode: vip
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 3
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    networks:
      - frontend-net

networks:
  frontend-net: 
    driver: overlay
    attachable: true