version: '3.8'

services:
  frontend:
    image: abhishekak71/akshopping-frontend:latest
    deploy:
      replicas: 3
    ports:
      - 3000:80
    networks:
      - frontend-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  frontend-net:
    driver: overlay
    attachable: true